import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import HeroSection from "@/components/HeroSection";
import ServiceSection from "@/components/ServiceSection";
import WhyWe from "@/components/WhyWe";
import ContactSections from "@/components/ContactUs";
import OurResult from "@/components/OurResult";
import Review from "@/components/Review";
import DiscountBanner from "@/components/Discount";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <HeroSection />
        <ServiceSection />
        <WhyWe />
        <DiscountBanner />
        <OurResult />
        <Review />
        <ContactSections />

        {/* {children} */}
        <Footer />
      </body>
    </html>
  );
}
